### ISSUE TITLE
Programmatic use not working

### ISSUE THREAD

**Issue by Papooch** [j-d-carmichael/boats#87] opened 2024-03-01 15:54 UTC
**Describe the bug**
When trying to import `boats` programmatically, I get the following error:
```
Error: Cannot find module '<path-to-repo>/node_modules/boats/src/index.js'. Please verify that the package.json has a valid "main" entry
```

**To Reproduce**
include `import boats from 'boats'` (or the CJS equivalent) in a source file and run it.

**Expected behavior**
As per the [docs](https://j-d-carmichael.github.io/boats/#/?id=programmatic-use)
> You can also use BOATS programmatically, just require (import if you are using a bundler) the lib into your project.

I would expect this to work and provide some programmatic API.

**Comment by j-d-carmichael** [comment] 2024-03-02 07:17
Hi,

Could you show some code of how you're importing?

Thanks, 
John

**Comment by p-mcgowan** [comment] 2024-03-02 14:22
the issue is `main` in package.json doesn't point to build/src but src, which doesn't exist after an install.

steps to repro
```bash
mkdir test
cd test
npm init --yes
npm i boats
node -p 'require("boats")'
```

**Comment by p-mcgowan** [comment] 2024-03-02 14:50
although that won't fix it anyway - it looks like the index exports the `default` key from 4 files, so it won't work anyway.

You would have to do something like `require('boats/build/src/Template').default`  in order to use those files

**Comment by j-d-carmichael** [comment] 2024-03-28 16:39
Dang! 

I'm pretty slammed at the moment so not sure i have the time until next month... PR would be very welcomed :)

**Comment by j-d-carmichael** [comment] 2024-08-08 17:18
@Papooch I've decided as I don't have time to work on this feature to instead remove programmatic use.

If you would like to expose boats in a programmatic way a PR would be welcomed.

The section of boats to expose would be:
https://github.com/j-d-carmichael/boats/blob/main/src/cli.ts#L55
to 
https://github.com/j-d-carmichael/boats/blob/main/src/cli.ts#L77

Ideally, the cli.ts file would call a new function or class named "boats" and the package.json would both export the types and the said file.

I would imagine something like added to the package json file:
```
  "main": "build/src/boats.js",
  "typings": "build/src/boats.d.ts",
```

For now though, there is no longer an export and I will close this PR.

**Closed by j-d-carmichael** 2024-08-08 17:18 UTC
Labels: bug
